name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rsync deployment
        env:
          dest: "doggo@165.227.163.13:/srv/web/cdn"
        run: |
          echo "${{secrets.SSH_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -rave "ssh -i ./deploy_key -o StrictHostKeyChecking=no" --exclude '.github' --exclude 'deploy_key' --exclude '.git' --delete ./* ${{env.dest}}
